import { DatabaseSchema } from './types';
import bcrypt from 'bcryptjs';

// Pre-computed hash for 'admin123'
const defaultPasswordHash = bcrypt.hashSync('admin123', 10);

export const initialData: DatabaseSchema = {
  users: [
    {
      id: 'usr_admin_01',
      name: 'Administrador TECH7',
      email: 'admin@tech7.com.br',
      passwordHash: defaultPasswordHash,
      role: 'ADMIN',
      createdAt: new Date().toISOString(),
    },
  ],
  settings: {
    id: 'default',
    logoUrl: '/brand/logo.svg',
    logoMobileUrl: '/brand/logo.svg',
    loginLogoUrl: '',
    faviconUrl: '/favicon.svg',
    primaryColor: '#00E676',
    secondaryColor: '#0B0F14',
    heroTitle: 'Soluções tecnológicas para empresas',
    heroSubtitle: 'Equipamentos, soluções audiovisuais e tecnologia corporativa para transformar a forma como as empresas trabalham e se conectam.',
    heroBadge: 'TECNOLOGIA CORPORATIVA B2B DE ALTA PERFORMANCE',
    heroImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
    whatsappNumber: '5511999999999',
    whatsappDefaultMessage: 'Olá, gostaria de receber mais informações.',
    whatsappProductMessage: 'Olá, estou interessado no produto [NOME DO PRODUTO]. Gostaria de receber mais informações.',
    contactEmail: 'contato@tech7electronics.com.br',
    contactPhone: '+55 (11) 3456-7890',
    address: 'Av. Paulista, 1578 - Bela Vista, São Paulo - SP, Brasil',
    linkedinUrl: 'https://linkedin.com/company/tech7-electronics',
    instagramUrl: 'https://instagram.com/tech7electronics',
    updatedAt: new Date().toISOString(),
  },
  categories: [
    {
      id: 'cat_01',
      name: 'Celulares',
      slug: 'celulares',
      description: 'Smartphones e dispositivos móveis robustos para frotas corporativas com gestão remota e segurança avançada.',
      image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80',
      order: 1,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cat_02',
      name: 'Computadores',
      slug: 'computadores',
      description: 'Workstations, desktops e ultrabooks empresariais homologados para máxima produtividade, durabilidade e desempenho multitarefa.',
      image: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=800&q=80',
      order: 2,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cat_03',
      name: 'Sala de conferências',
      slug: 'sala-de-conferencias',
      description: 'Sistemas inteligentes de videoconferência 4K, microfones omnidirecionais e telas interativas para colaboração híbrida.',
      image: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=800&q=80',
      order: 3,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cat_04',
      name: 'Brindes corporativos',
      slug: 'brindes-corporativos',
      description: 'Eletrônicos premium personalizados com a marca da sua empresa: fones com cancelamento de ruído, powerbanks e kits executivos.',
      image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      order: 4,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  products: [
    {
      id: 'prod_01',
      name: 'Smartphone Corporativo TechMobile Secure 5G',
      slug: 'smartphone-corporativo-techmobile-secure-5g',
      sku: 'T7-MOB-5G01',
      brand: 'TECH7 Mobility',
      model: 'TM-Enterprise 5G',
      categoryId: 'cat_01',
      shortDesc: 'Dispositivo móvel com criptografia em nível de hardware, suporte a MDM corporativo e bateria de ultra-duração.',
      description: 'Desenvolvido especificamente para demandas empresariais críticas, o TechMobile Secure 5G integra plataforma de gerenciamento remoto seguro, resistência militar MIL-STD-810H e suporte garantido de atualizações de segurança por 5 anos.',
      features: [
        'Homologação para gerenciamento corporativo via MDM / EMM',
        'Criptografia dedicada por chip de segurança dedicado',
        'Bateria de 5.500 mAh com recarga rápida de 65W',
        'Certificação IP68 de resistência contra água e poeira',
        'Suporte a Dual SIM com tecnologia eSIM integrada',
      ],
      specs: {
        'Conectividade': '5G Ultra-Wideband, Wi-Fi 6E, Bluetooth 5.3, NFC',
        'Processador': 'Octa-Core 3.2 GHz de alta eficiência térmica',
        'Memória RAM': '12 GB LPDDR5X',
        'Armazenamento': '256 GB UFS 4.0 criptografado',
        'Tela': '6.67" AMOLED Full HD+ com 120Hz adaptativo',
        'Câmeras': 'Traseira 50 MP com OIS + Frontal 32 MP para vídeo-chamadas',
        'Garantia Corporativa': '24 meses com substituição expressa no Brasil',
      },
      mainImage: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80',
      galleryImages: [
        'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
      ],
      order: 1,
      isActive: true,
      inquiriesCount: 14,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod_02',
      name: 'Workstation Profissional UltraDesk 16-Core',
      slug: 'workstation-profissional-ultradesk-16-core',
      sku: 'T7-WS-16C',
      brand: 'TECH7 Computing',
      model: 'UD-9000X Pro',
      categoryId: 'cat_02',
      shortDesc: 'Estação de trabalho de alto desempenho para engenharia, renderização 3D, análise de dados e arquitetura.',
      description: 'Projetada para fluxos de trabalho que não podem parar. Equipada com componentes de classe industrial, refrigeração líquida ultra silenciosa e certificação ISV para as principais aplicações profissionais de engenharia e modelagem.',
      features: [
        'Certificação de estabilidade operacional 24/7 ininterrupta',
        'Fonte modular 80 Plus Platinum com PFC ativo',
        'Chassi com fluxo de ar otimizado e filtros magnéticos anti-poeira',
        'Segurança física com trava Kensington e sensor de intrusão no gabinete',
      ],
      specs: {
        'Processador': '16 Núcleos / 32 Threads até 5.7 GHz com 64MB Cache',
        'Memória RAM': '64 GB DDR5 5600MHz (Expansível até 192 GB)',
        'Placa de Vídeo': 'NVIDIA RTX Profissional 16GB GDDR6 com ECC',
        'Armazenamento': '2 TB NVMe PCIe Gen 4 (7000 MB/s)',
        'Rede': 'Dual LAN 2.5 GbE + Wi-Fi 6E Pro',
        'Sistema Operacional': 'Windows 11 Pro para Estações de Trabalho',
        'Garantia': '36 meses On-Site para todo o território nacional',
      },
      mainImage: 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?auto=format&fit=crop&w=800&q=80',
      galleryImages: [
        'https://images.unsplash.com/photo-1587831990711-23ca6441447b?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=800&q=80',
      ],
      order: 2,
      isActive: true,
      inquiriesCount: 22,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod_03',
      name: 'Ultrabook Corporativo ThinkFleet 14" Slim',
      slug: 'ultrabook-corporativo-thinkfleet-14-slim',
      sku: 'T7-NB-TF14',
      brand: 'TECH7 Computing',
      model: 'TF-14 Pro Carbon',
      categoryId: 'cat_02',
      shortDesc: 'Notebook executivo com chassi em liga de magnésio, peso de 1.1kg e autonomia de até 16 horas.',
      description: 'A ferramenta definitiva para executivos e profissionais móveis. Combina elegância estética corporativa, teclado retroiluminado à prova de respingos, leitor biométrico integrado no botão liga/desliga e tecnologia de redução de ruído por inteligência artificial.',
      features: [
        'Peso ultra leve de apenas 1.18 kg',
        'Câmera Full HD IR com obturador físico de privacidade',
        'Bateria com carregamento rápido: 80% em 45 minutos',
        'Duas portas Thunderbolt 4 com suporte a carregamento e display',
      ],
      specs: {
        'Processador': 'Intel Core i7 vPro 13ª Geração (10 Núcleos)',
        'Memória RAM': '32 GB LPDDR5 integrados em canal duplo',
        'Armazenamento': '1 TB SSD NVMe M.2 PCIe 4.0',
        'Tela': '14.0" WQXGA (2560x1600) IPS Anti-reflexo 400 nits',
        'Bateria': '65 Wh com autonomia testada de 16 horas de uso de escritório',
        'Segurança': 'Chip TPM 2.0 + Leitor de Impressão Digital + Câmera Windows Hello',
        'Garantia': '36 meses com atendimento prioritário',
      },
      mainImage: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80',
      galleryImages: [
        'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80',
      ],
      order: 3,
      isActive: true,
      inquiriesCount: 19,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod_04',
      name: 'Sistema de Videoconferência 4K All-in-One Bar',
      slug: 'sistema-videoconferencia-4k-all-in-one-bar',
      sku: 'T7-CONF-4KB1',
      brand: 'TECH7 Visual',
      model: 'OmniBar 4K AI',
      categoryId: 'cat_03',
      shortDesc: 'Barra inteligente de conferência com câmera 4K e-PTZ, enquadramento automático por IA e matriz de 6 microfones.',
      description: 'Transforme qualquer sala de reunião corporativa em um ambiente de conferência imersivo. Compatível nativamente com Microsoft Teams, Zoom Rooms e Google Meet. O recurso de autoframing acompanha o interlocutor ativo e cancela ecos de digitação e ruídos de ar-condicionado.',
      features: [
        'Enquadramento inteligente (Auto Framing) e rastreamento de voz por IA',
        'Matriz de 6 microfones com cancelamento acústico de ruído até 8 metros',
        'Alto-falantes estéreo de alta fidelidade com graves calibrados para voz humana',
        'Conexão Plug & Play USB-C para notebooks de visitantes',
      ],
      specs: {
        'Resolução de Vídeo': '4K Ultra HD a 30fps / 1080p a 60fps',
        'Campo de Visão (FOV)': '120° grande angular sem distorção periférica',
        'Zoom': '5x Digital e-PTZ suave',
        'Alcance de Áudio': 'Captação circular 360° em raio de até 8 metros',
        'Conexões': 'HDMI Out, USB 3.0 Type-C, Ethernet RJ45, Bluetooth',
        'Compatibilidade': 'Certificado para Teams, Zoom, Webex e Meet',
        'Garantia': '24 meses com suporte de firmware contínuo',
      },
      mainImage: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=800&q=80',
      galleryImages: [
        'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=800&q=80',
      ],
      order: 4,
      isActive: true,
      inquiriesCount: 31,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod_05',
      name: 'Smart Display Interativo Touch 65" 4K Whiteboard',
      slug: 'smart-display-interativo-touch-65-4k-whiteboard',
      sku: 'T7-CONF-DISP65',
      brand: 'TECH7 Visual',
      model: 'BoardTouch 65-Pro',
      categoryId: 'cat_03',
      shortDesc: 'Painel touchscreen capacitivo 4K com lousa digital integrada e suporte a compartilhamento sem fio de tela.',
      description: 'Ideal para salas de diretoria, salas de treinamento e salas de crise. Permite até 20 pontos de toque simultâneos com caneta passiva ou dedo, anotações instantâneas sobre qualquer apresentação e exportação para PDF com um toque.',
      features: [
        'Vidro temperado anti-reflexo com resistência a impacto 7H',
        'Tecnologia Zero Gap para precisão milimétrica de escrita manual',
        'Compartilhamento sem fio a partir de Windows, macOS, iOS e Android',
        'Slot padrão OPS para expansão com módulo PC interno',
      ],
      specs: {
        'Tamanho do Painel': '65 polegadas D-LED Anti-Glare',
        'Resolução': '3840 x 2160 (4K UHD) com brilho de 450 cd/m²',
        'Tempo de Resposta': '6ms com precisão de toque < 1mm',
        'Entradas': '3x HDMI 2.0, 1x DisplayPort, 4x USB Touch, 1x Type-C 65W PD',
        'Áudio Integrado': '2 alto-falantes de 20W estéreo frontais',
        'Garantia': '36 meses com garantia on-site',
      },
      mainImage: 'https://images.unsplash.com/photo-1542744094-3a31727201b3?auto=format&fit=crop&w=800&q=80',
      galleryImages: [
        'https://images.unsplash.com/photo-1542744094-3a31727201b3?auto=format&fit=crop&w=800&q=80',
      ],
      order: 5,
      isActive: true,
      inquiriesCount: 16,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod_06',
      name: 'Kit Executivo TechPower Induction Premium',
      slug: 'kit-executivo-techpower-induction-premium',
      sku: 'T7-GIFT-PWR01',
      brand: 'TECH7 Corporate Gifts',
      model: 'Executive Power Set Black',
      categoryId: 'cat_04',
      shortDesc: 'Conjunto corporativo de alto padrão com Powerbank 20.000mAh magnético, carregador wireless e case em alumínio anodizado.',
      description: 'Um presente corporativo que traduz modernidade e sofisticação para clientes estratégicos e lideranças executivas. Personalizável a laser com a logomarca da sua empresa em tiragens a partir de 25 unidades.',
      features: [
        'Personalização a laser de alta precisão na superfície de alumínio',
        'Estojo executivo rígido de apresentação com berço magnético',
        'Compatibilidade com MagSafe e indução Qi universal',
        'Homologação de segurança Anatel e proteção contra sobrecarga térmica',
      ],
      specs: {
        'Capacidade do Powerbank': '20.000 mAh com células de polímero de lítio classe A',
        'Potência Wireless': '15W Fast Wireless Charging',
        'Potência USB-C PD': '65W Power Delivery bidirecional (carrega notebooks)',
        'Acabamento': 'Alumínio aeroespacial anodizado em Cinza Grafite ou Preto Fosco',
        'Pedido Mínimo Corporativo': 'Lotes a partir de 25 unidades com personalização',
        'Garantia': '12 meses contra defeitos de fabricação',
      },
      mainImage: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&w=800&q=80',
      galleryImages: [
        'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&w=800&q=80',
      ],
      order: 6,
      isActive: true,
      inquiriesCount: 45,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  clients: [
    {
      id: 'cli_01',
      name: 'Nexus Inovação Corporativa',
      logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=300&q=80',
      website: 'https://nexus.exemplo.com.br',
      order: 1,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cli_02',
      name: 'OmniTech Soluções Globais',
      logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80',
      website: 'https://omnitech.exemplo.com.br',
      order: 2,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cli_03',
      name: 'Apex Logistics Brasil',
      logo: 'https://images.unsplash.com/photo-1516876437184-593fda40c7ce?auto=format&fit=crop&w=300&q=80',
      website: 'https://apexlog.exemplo.com.br',
      order: 3,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cli_04',
      name: 'Vortex Capital & Banking',
      logo: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=300&q=80',
      website: 'https://vortex.exemplo.com.br',
      order: 4,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cli_05',
      name: 'Horizon Cloud Infrastructure',
      logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=300&q=80',
      website: 'https://horizon.exemplo.com.br',
      order: 5,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cli_06',
      name: 'Prime Healthcare Tech',
      logo: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=300&q=80',
      website: 'https://primehealth.exemplo.com.br',
      order: 6,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  whatsappInquiries: [
    {
      id: 'inq_01',
      productId: 'prod_06',
      productName: 'Kit Executivo TechPower Induction Premium',
      createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      ipAddress: '189.120.45.10',
    },
    {
      id: 'inq_02',
      productId: 'prod_04',
      productName: 'Sistema de Videoconferência 4K All-in-One Bar',
      createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
      ipAddress: '201.88.92.33',
    },
    {
      id: 'inq_03',
      productId: 'prod_02',
      productName: 'Workstation Profissional UltraDesk 16-Core',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
      ipAddress: '177.34.12.89',
    },
    {
      id: 'inq_04',
      productId: 'prod_01',
      productName: 'Smartphone Corporativo TechMobile Secure 5G',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      ipAddress: '191.240.11.20',
    },
  ],
  videos: [
    {
      id: 'vid_01',
      title: 'Ecossistema Corporativo de Alta Conectividade',
      description: 'Demonstração das soluções integradas TECH7 para escritórios inteligentes e hubs executivos.',
      videoUrl: '/uploads/videos/tech7-solucao-corporativa.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=720&q=80',
      category: 'LANÇAMENTO',
      isActive: true,
      order: 1,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'vid_02',
      title: 'Painéis Interativos 4K Ultra Touch',
      description: 'Colaboração imersiva em tempo real para salas de reuniões e centros de comando corporativos.',
      videoUrl: '/uploads/videos/tech7-painel-interativo.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=720&q=80',
      category: 'INOVAÇÃO',
      isActive: true,
      order: 2,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'vid_03',
      title: 'Infraestrutura de TI e Servidores de Alta Densidade',
      description: 'Segurança de dados de ponta a ponta e redundância crítica para redes empresariais.',
      videoUrl: '/uploads/videos/tech7-infraestrutura-ti.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=720&q=80',
      category: 'TECNOLOGIA',
      isActive: true,
      order: 3,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'vid_04',
      title: 'Videoconferência com IA e Áudio Espacial',
      description: 'Cancelamento inteligente de ruído e enquadramento dinâmico com tecnologia acústica avançada.',
      videoUrl: '/uploads/videos/tech7-videoconferencia.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=720&q=80',
      category: 'DESTAQUE',
      isActive: true,
      order: 4,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'vid_05',
      title: 'Workstations Gráficas para Engenharia e IA',
      description: 'Poder de computação dedicado para projetos complexos, modelagem 3D e processamento pesado.',
      videoUrl: '/uploads/videos/tech7-workstation.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=720&q=80',
      category: 'NOVO',
      isActive: true,
      order: 5,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  reviews: [
    {
      id: 'rev_01',
      customerName: 'Carlos Almeida',
      companyName: 'Diretor de Operações — LogiTech Brasil',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      rating: 5,
      comment: 'Excelente atendimento e muito profissionalismo. A equipe da TECH7 nos ajudou a encontrar a infraestrutura adequada para as novas sedes da nossa empresa.',
      reviewDate: 'Há 1 mês',
      isVerified: true,
      isActive: true,
      order: 1,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'rev_02',
      customerName: 'Mariana Vasconcelos',
      companyName: 'Gerente de TI — Grupo Nexus Capital',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
      rating: 5,
      comment: 'Implementamos estações de trabalho e salas de reunião inteligentes com a TECH7. Suporte ágil e equipamentos homologados de altíssimo nível.',
      reviewDate: 'Há 2 meses',
      isVerified: true,
      isActive: true,
      order: 2,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'rev_03',
      customerName: 'Roberto Silveira',
      companyName: 'CTO — InovaMed Soluções Médicas',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      rating: 5,
      comment: 'Parceria de mais de 3 anos com a TECH7. Sempre pontuais na entrega e com consultoria técnica que entende a real criticidade do ambiente corporativo.',
      reviewDate: 'Há 3 meses',
      isVerified: true,
      isActive: true,
      order: 3,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'rev_04',
      customerName: 'Fernanda Guimarães',
      companyName: 'Head de Infraestrutura — FinTech Horizon',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
      rating: 5,
      comment: 'A consultoria B2B deles faz toda a diferença. Atenderam com maestria nossa demanda de servidores e segurança com agilidade surpreendente.',
      reviewDate: 'Há 4 meses',
      isVerified: true,
      isActive: true,
      order: 4,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'rev_05',
      customerName: 'Eduardo Castro',
      companyName: 'Coordenador de Compras — Construtora Alpha',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      rating: 5,
      comment: 'Melhor relação custo-benefício em tecnologia corporativa. Processo transparente de cotação e entrega antes do prazo acordado.',
      reviewDate: 'Há 5 meses',
      isVerified: true,
      isActive: true,
      order: 5,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};
